<?php
echo '
</HEAD>

<BODY>
<div id="main-container">
	<div id="header">
		<div id="logo-container">
			<img id="logo" src="' . $banner_src . '">
		</div>
		
		<div id="top-link-container">
			<a href="' . $domain_base . 'index.php" class="top-link" style="clear:left;">Home</a>
			<a href="' . $domain_base . 'team.php" class="top-link">Our Team</a>
			<a href="' . $domain_base . 'resource.php" class="top-link">Resources</a>
			<a href="' . $domain_base . 'events.php" class="top-link">Events</a>
			<a href="' . $domain_base . 'contact.php" class="top-link" style="clear:right;">Contact Us</a>		
		</div>
	</div>
	
	<div id="body">';
?>