<?php
echo '
<!DOCTYPE HTML>
<HTML>

<HEAD>
<link rel="shortcut icon" href="http://stsontario.org/favicon.ico" type="image/x-icon" />
<meta charset="utf-8"/>
<meta name="robots" content="index, follow">
<meta name="author" content="Omar Abdel Bari">

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<style>
BODY {
	font-family:Tahoma;
	font-size:16px;
}

#main-container {
	margin:1% auto;
	padding:1% 0;
	width:970px;
	background-color:#E4E4E4;
}

#header {
	text-align:center;
}

#logo {
	width:100%;
	height:auto;
	margin:0 auto;
}

#top-link-container {
	width:100%;
	clear:both;
	margin:0 auto;
	text-align:center;
}

#top-link-container a {
	display:inline-block;
	width:150px;
	border-style:solid none;
	border-width:0.3vh;
	margin:0 10px;
	text-transform:uppercase;
	text-decoration:none;
	color:#000000;
	font-size:18px;
}

#body {
	clear:both;
	margin:20px auto 0 auto;
	padding:20px 20px 20px 20px;
	width:900px;
	background-color:#DCDCDC;
	border-radius:7px;
	overflow:auto;
}

.title {
	font-size:28px;
	display:block;
}

.header1 {
	font-size:24px;
	display:block;
	text-transform:uppercase;
}

.header2 {
	font-size:22px;
	display:block;
}

.bold1 {
	font-size:16px;
	font-weight:600;
}

.bold2 {
	font-size:20px;
	font-weight:600;
}

.bold3 {
	font-size:24px;
	font-weight:600;
}

#body a {
	text-decoration:none;
	color:#000000;
}
</style>';
?>